### PR TITLE
require puppetlabs/stdlib 9

### PR DESCRIPTION
**Pull request by robertc99**
#### Pull Request (PR) description
ensure compatability with latest stdlib

#### This Pull Request (PR) fixes the following issues
n/a

### CODE REVIEW

**Comment by bastelfreak** [comment]
@robertc99 please update spec/spec_helper_acceptance.rb to allow newer versions of apache/java modules. We also need to wait until a newer version of puppetlabs/java is released.

**Comment by robertc99** [comment]
I updated spec/spec_helper_acceptance.rb as requested.
Its still failing the check, but the error makes no sense to me.

**Comment by bastelfreak** [comment]
@robertc99 the problem is that the latest version of puppetlabs/java doesn't allow puppetlabs/stdlib 9. We need to wait for a new release.

**Comment by robertc99** [comment]
ok, the repo head has been updated. they just need to do a release.

**Comment by robertc99** [comment]
looks like a new java has been released. how do I get it to redo the checks?

**Comment by bastelfreak** [comment]
mhm I'm currently not sure why this fails :thinking: . I asked on slack.

**Comment by bastelfreak** [comment]
It's failing because latest apache doesn't allow latest concat. and older concat don't allow latest stdlib. I raised https://github.com/puppetlabs/puppetlabs-apache/pull/2426

**Comment by robertc99** [comment]
looks like the apache bit is done

**Comment by robertc99** [comment]
can you force the checks to rerun?

**Comment by robertc99** [comment]
thanks.
now we just need a release...

**Pull request merged**
