### PR TITLE
modulesync 4.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 4.0.0

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Fails on EL6 because it can't connect to the right hostname. I recall that there were issues on that with beaker-docker which is why it previously didn't ran on it either. Recommending to drop EL6 in the module.

**Review by ekohl — APPROVED** [review]

**Comment by bastelfreak** [comment]
I created https://github.com/voxpupuli/puppet-trusted_ca/issues/30 so we've CentOS 6 properly mentioned in the CHANGELOG.md

**Comment by ekohl** [comment]
A bit redundant since I already opened https://github.com/voxpupuli/puppet-trusted_ca/pull/29 that was automatically merged as part of this PR.

**Comment by bastelfreak** [comment]
ah okay, will remove #30 from the changelog then

**Pull request merged**
